//Creating Items
const body = document.querySelector("body");
const container = document.createElement("div");
const row1 = document.createElement("div");
const column1 = document.createElement("div");
const column2 = document.createElement("div");
const column3 = document.createElement("div");
const column4 = document.createElement("div");
const column5 = document.createElement("div");
const column6 = document.createElement("div");
const column7 = document.createElement("div");
const column8 = document.createElement("div");
const column9 = document.createElement("div");
const column10 = document.createElement("div");
const column11 = document.createElement("div");
const column12 = document.createElement("div");
const column13 = document.createElement("div");
const column14 = document.createElement("div");
const column15 = document.createElement("div");
const column16 = document.createElement("div");
const row2 = document.createElement("div");
const column21 = document.createElement("div");
const column22 = document.createElement("div");
const column23 = document.createElement("div");
const column24 = document.createElement("div");
const column25 = document.createElement("div");
const column26 = document.createElement("div");
const column27 = document.createElement("div");
const column28 = document.createElement("div");
const column29 = document.createElement("div");
const column210 = document.createElement("div");
const column211 = document.createElement("div");
const column212 = document.createElement("div");
const column213 = document.createElement("div");
const column214 = document.createElement("div");
const column215 = document.createElement("div");
const column216 = document.createElement("div");
const row3 = document.createElement("div");
const column31 = document.createElement("div");
const column32 = document.createElement("div");
const column33 = document.createElement("div");
const column34 = document.createElement("div");
const column35 = document.createElement("div");
const column36 = document.createElement("div");
const column37 = document.createElement("div");
const column38 = document.createElement("div");
const column39 = document.createElement("div");
const column310 = document.createElement("div");
const column311 = document.createElement("div");
const column312 = document.createElement("div");
const column313 = document.createElement("div");
const column314 = document.createElement("div");
const column315 = document.createElement("div");
const column316 = document.createElement("div");
const row4 = document.createElement("div");
const column41 = document.createElement("div");
const column42 = document.createElement("div");
const column43 = document.createElement("div");
const column44 = document.createElement("div");
const column45 = document.createElement("div");
const column46 = document.createElement("div");
const column47 = document.createElement("div");
const column48 = document.createElement("div");
const column49 = document.createElement("div");
const column410 = document.createElement("div");
const column411 = document.createElement("div");
const column412 = document.createElement("div");
const column413 = document.createElement("div");
const column414 = document.createElement("div");
const column415 = document.createElement("div");
const column416 = document.createElement("div");
const row5 = document.createElement("div");
const column51 = document.createElement("div");
const column52 = document.createElement("div");
const column53 = document.createElement("div");
const column54 = document.createElement("div");
const column55 = document.createElement("div");
const column56 = document.createElement("div");
const column57 = document.createElement("div");
const column58 = document.createElement("div");
const column59 = document.createElement("div");
const column510 = document.createElement("div");
const column511 = document.createElement("div");
const column512 = document.createElement("div");
const column513 = document.createElement("div");
const column514 = document.createElement("div");
const column515 = document.createElement("div");
const column516 = document.createElement("div");
const row6 = document.createElement("div");
const column61 = document.createElement("div");
const column62 = document.createElement("div");
const column63 = document.createElement("div");
const column64 = document.createElement("div");
const column65 = document.createElement("div");
const column66 = document.createElement("div");
const column67 = document.createElement("div");
const column68 = document.createElement("div");
const column69 = document.createElement("div");
const column610 = document.createElement("div");
const column611 = document.createElement("div");
const column612 = document.createElement("div");
const column613 = document.createElement("div");
const column614 = document.createElement("div");
const column615 = document.createElement("div");
const column616 = document.createElement("div");
const row7 = document.createElement("div");
const row8 = document.createElement("div");
const row9 = document.createElement("div");
const row10 = document.createElement("div");
const row11 = document.createElement("div");
const row12 = document.createElement("div");
const row13 = document.createElement("div");
const row14 = document.createElement("div");
const row15 = document.createElement("div");
const row16 = document.createElement("div");

//Creating classes
container.classList.toggle("container");
row1.classList.toggle("row");
column1.classList.toggle("column");
column2.classList.toggle("column");
column3.classList.toggle("column");
column4.classList.toggle("column");
column5.classList.toggle("column");
column6.classList.toggle("column");
column7.classList.toggle("column");
column8.classList.toggle("column");
column9.classList.toggle("column");
column10.classList.toggle("column");
column11.classList.toggle("column");
column12.classList.toggle("column");
column13.classList.toggle("column");
column14.classList.toggle("column");
column15.classList.toggle("column");
column16.classList.toggle("column");
row2.classList.toggle("row");
column21.classList.toggle("column");
column22.classList.toggle("column");
column23.classList.toggle("column");
column24.classList.toggle("column");
column25.classList.toggle("column");
column26.classList.toggle("column");
column27.classList.toggle("column");
column28.classList.toggle("column");
column29.classList.toggle("column");
column210.classList.toggle("column");
column211.classList.toggle("column");
column212.classList.toggle("column");
column213.classList.toggle("column");
column214.classList.toggle("column");
column215.classList.toggle("column");
column216.classList.toggle("column");
row3.classList.toggle("row");
column31.classList.toggle("column");
column32.classList.toggle("column");
column33.classList.toggle("column");
column34.classList.toggle("column");
column35.classList.toggle("column");
column36.classList.toggle("column");
column37.classList.toggle("column");
column38.classList.toggle("column");
column39.classList.toggle("column");
column310.classList.toggle("column");
column311.classList.toggle("column");
column312.classList.toggle("column");
column313.classList.toggle("column");
column314.classList.toggle("column");
column315.classList.toggle("column");
column316.classList.toggle("column");
//container class
container.style.maxWidth = "1200px";
container.style.margin = "0 auto";
//Putting things where they belong
body.appendChild(container);
container.appendChild(row1);
row1.appendChild(column1);
row1.appendChild(column2);
row1.appendChild(column3);
row1.appendChild(column4);
row1.appendChild(column5);
row1.appendChild(column6);
row1.appendChild(column7);
row1.appendChild(column8);
row1.appendChild(column9);
row1.appendChild(column10);
row1.appendChild(column11);
row1.appendChild(column12);
row1.appendChild(column13);
row1.appendChild(column14);
row1.appendChild(column15);
row1.appendChild(column16);
container.appendChild(row2);
row2.appendChild(column21);
row2.appendChild(column22);
row2.appendChild(column23);
row2.appendChild(column24);
row2.appendChild(column25);
row2.appendChild(column26);
row2.appendChild(column27);
row2.appendChild(column28);
row2.appendChild(column29);
row2.appendChild(column210);
row2.appendChild(column211);
row2.appendChild(column212);
row2.appendChild(column213);
row2.appendChild(column214);
row2.appendChild(column215);
row2.appendChild(column216);
container.appendChild(row3);
row3.appendChild(column31);
row3.appendChild(column32);
row3.appendChild(column33);
row3.appendChild(column34);
row3.appendChild(column35);
row3.appendChild(column36);
row3.appendChild(column37);
row3.appendChild(column38);
row3.appendChild(column39);
row3.appendChild(column310);
row3.appendChild(column311);
row3.appendChild(column312);
row3.appendChild(column313);
row3.appendChild(column314);
row3.appendChild(column315);
row3.appendChild(column316);
container.appendChild(row4);
container.appendChild(row5);
container.appendChild(row6);
container.appendChild(row7);
container.appendChild(row8);
container.appendChild(row9);
container.appendChild(row10);
container.appendChild(row11);
container.appendChild(row12);
container.appendChild(row13);
container.appendChild(row14);
container.appendChild(row15);
container.appendChild(row16);





